name: parchis_reverse_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  video_player: ^2.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # ğŸ” Firebase & Authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_database: ^10.4.0
  
  # ğŸ“± Social Login
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.1.6
  
  # ğŸŒ HTTP & Connectivity
  http: ^1.1.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/audio/effects/
    - assets/audio/music/
    - assets/video/
